#!/usr/bin/env bash
# Reads the root VERSION file and regenerates language-specific version sources.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VERSION="$(cat "$REPO_ROOT/VERSION" | tr -d '[:space:]')"
IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"

echo "Generating version files for $VERSION ..."

# Swift
cat > "$REPO_ROOT/swift/src/GeneratedVersion.swift" << EOF
/// Auto-generated from VERSION file — do not edit manually.
/// Run: scripts/generate-version.sh to regenerate.
internal enum GeneratedVersion {
    static let string = "$VERSION"
    static let major = $MAJOR
    static let minor = $MINOR
    static let patch = $PATCH
}
EOF

echo "  swift/src/GeneratedVersion.swift"

# Kotlin is generated by Gradle build task (build.gradle.kts)
# Rust is injected via build.rs at compile time

echo "Done."
